version: '3'

tasks:
  run:
    cmds:
      - go run ./cmd/runner/main.go -config=./config/local.yml.yml
  migrate:run:
    desc: Запуск миграций БД
    cmds:
      - go run ./cmd/migration/ch/main.go
      - go run ./cmd/migration/pg/main.go