postgres:
  type:
  host:
  port:
  name:
  user:
  password:
  schema:
  maxAttempts:
  attemptDelay:
  migrationPath:

clickhouse:
  type:
  host:
  port:
  name:
  user:
  password:
  migrationPath:
  maxAttempts:
  attemptDelay: